// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7bNjHqhvDo0PlsCoeqAJrqt-GqNl6y4A',
    appId: '1:105733141370:ios:894539053ae131ee97dcc3',
    messagingSenderId: '105733141370',
    projectId: 'gestura-app-2e9fd',
    storageBucket: 'gestura-app-2e9fd.firebasestorage.app',
    iosBundleId: 'com.example.gesturaclaude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFic7ZNRSNtnMWryceScbvtt21StyeWPE',
    appId: '1:105733141370:web:7eb4560acd71f38697dcc3',
    messagingSenderId: '105733141370',
    projectId: 'gestura-app-2e9fd',
    authDomain: 'gestura-app-2e9fd.firebaseapp.com',
    storageBucket: 'gestura-app-2e9fd.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFic7ZNRSNtnMWryceScbvtt21StyeWPE',
    appId: '1:105733141370:web:7eb4560acd71f38697dcc3',
    messagingSenderId: '105733141370',
    projectId: 'gestura-app-2e9fd',
    authDomain: 'gestura-app-2e9fd.firebaseapp.com',
    storageBucket: 'gestura-app-2e9fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7bNjHqhvDo0PlsCoeqAJrqt-GqNl6y4A',
    appId: '1:105733141370:ios:894539053ae131ee97dcc3',
    messagingSenderId: '105733141370',
    projectId: 'gestura-app-2e9fd',
    storageBucket: 'gestura-app-2e9fd.firebasestorage.app',
    iosBundleId: 'com.example.gesturaclaude',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATpYdtivgLle6b1V3zNSsqz8RkfqGXCPE',
    appId: '1:105733141370:android:06a640e9254f02a097dcc3',
    messagingSenderId: '105733141370',
    projectId: 'gestura-app-2e9fd',
    storageBucket: 'gestura-app-2e9fd.firebasestorage.app',
  );

}